import { Bot, CheckCircle2, Clock3, MessageSquareText, Send, WalletCards } from "lucide-react";
import { queueTestMessage, saveAutomationRule } from "@/app/(crm)/actions";
import { createClient } from "@/lib/supabase/server";
import { shortDate } from "@/lib/utils";

type Rule = { id:string;automation_type:string;enabled:boolean;days_before:number;send_time:string;template_id:string;template:{name:string;body:string} };
const labels:Record<string,{title:string;description:string;icon:typeof Bot}> = {
  payment_reminder:{title:"Lembretes de cobrança",description:"Avisa antes do vencimento e repete diariamente enquanto houver saldo.",icon:WalletCards},
  payment_confirmation:{title:"Confirmação de pagamento",description:"Confirma automaticamente cada pagamento total ou parcial registrado.",icon:CheckCircle2},
  appointment_reminder:{title:"Lembretes de agendamento",description:"Lembra visitas e instalações e permite confirmar ou solicitar reagendamento.",icon:Clock3},
};

export async function AutomationSettings({error,saved,test}:{error?:string;saved?:boolean;test?:boolean}) {
  let rules:Rule[]=[]; let recent:Record<string,unknown>[]=[]; let phoneId=""; let loadError="";
  if(process.env.NEXT_PUBLIC_SUPABASE_URL){const db=await createClient(); const {data:profile}=await db.from("profiles").select("company_id").single(); if(profile?.company_id){const company=await db.from("companies").select("whatsapp_phone_number_id").eq("id",profile.company_id).single(); phoneId=company.data?.whatsapp_phone_number_id ?? ""; const result=await db.from("automation_rules").select("id,automation_type,enabled,days_before,send_time,template_id,template:message_templates(name,body)").eq("company_id",profile.company_id).order("automation_type"); rules=(result.data as unknown as Rule[])??[]; loadError=result.error?.message??""; const history=await db.from("outbound_messages").select("id,automation_type,phone,status,scheduled_at,sent_at,error_message").eq("company_id",profile.company_id).order("created_at",{ascending:false}).limit(12); recent=(history.data as unknown as Record<string,unknown>[])??[];}}
  return <div className="mx-auto max-w-6xl"><div className="mb-7"><div className="mb-3 flex h-11 w-11 items-center justify-center rounded-xl bg-forest text-white"><Bot className="h-5 w-5"/></div><h1 className="text-3xl font-black">Automações e chatbot</h1><p className="mt-1 text-sm text-ink/50">Cobranças, confirmações e agenda pelo WhatsApp Cloud API.</p></div>
    {(error||loadError)&&<p className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error||loadError}</p>}{saved&&<p className="mb-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">Automação atualizada.</p>}{test&&<p className="mb-5 rounded-xl bg-blue-50 p-4 text-sm text-blue-700">Mensagem de teste adicionada à fila.</p>}
    {!phoneId&&<div className="mb-5 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-sm text-amber-900"><b>Falta conectar o WhatsApp.</b> Cadastre o ID do número em Configurações → Identidade da empresa e configure os segredos descritos no README.</div>}
    <section className="grid gap-5 lg:grid-cols-3">{rules.length?rules.map(rule=><RuleCard rule={rule} key={rule.id}/>):<div className="card col-span-full p-8 text-center text-sm text-ink/45">Execute a migração <b>005_whatsapp_automations.sql</b> para criar as regras iniciais.</div>}</section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><form action={queueTestMessage} className="card p-5"><div className="flex items-center gap-2"><Send className="h-5 w-5 text-forest"/><h2 className="font-black">Testar fila</h2></div><p className="mt-1 text-xs text-ink/45">O processador enviará a mensagem na próxima execução.</p><label className="label mt-5">WhatsApp com DDD</label><input className="field" name="phone" placeholder="41999999999"/><label className="label mt-4">Mensagem</label><textarea className="field min-h-24" name="body" defaultValue="Olá! Esta é uma mensagem de teste da Marquinhos Calhas e Esquadrias."/><button className="button mt-4 w-full"><Send className="h-4 w-4"/>Adicionar à fila</button></form>
      <div className="card overflow-hidden"><div className="border-b p-5"><div className="flex items-center gap-2"><MessageSquareText className="h-5 w-5 text-forest"/><h2 className="font-black">Últimas mensagens</h2></div></div><div className="divide-y">{recent.length?recent.map(item=><div className="grid grid-cols-[1fr_auto] gap-3 p-4 text-sm" key={String(item.id)}><div><p className="font-bold">{String(item.automation_type).replaceAll("_"," ")}</p><p className="text-xs text-ink/45">{String(item.phone)} · {shortDate(String(item.scheduled_at).slice(0,10))}</p>{Boolean(item.error_message)&&<p className="mt-1 text-xs text-red-600">{String(item.error_message)}</p>}</div><Status value={String(item.status)}/></div>):<p className="p-8 text-center text-sm text-ink/45">Nenhuma mensagem processada.</p>}</div></div>
    </section>
  </div>;
}
function RuleCard({rule}:{rule:Rule}){const meta=labels[rule.automation_type]??{title:rule.automation_type,description:"",icon:Bot};const Icon=meta.icon;return <form action={saveAutomationRule} className="card flex flex-col p-5"><input type="hidden" name="rule_id" value={rule.id}/><input type="hidden" name="template_id" value={rule.template_id}/><div className="flex items-start justify-between gap-3"><span className="rounded-xl bg-cream p-2.5 text-forest"><Icon className="h-5 w-5"/></span><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" name="enabled" defaultChecked={rule.enabled} className="h-4 w-4 accent-forest"/>Ativa</label></div><h2 className="mt-4 font-black">{meta.title}</h2><p className="mt-1 min-h-10 text-xs leading-5 text-ink/45">{meta.description}</p><label className="label mt-4">Mensagem</label><textarea className="field min-h-36 flex-1 text-xs leading-5" name="body" defaultValue={rule.template.body}/><div className="mt-4 grid grid-cols-2 gap-3"><div><label className="label">Dias antes</label><input className="field" type="number" min="0" max="30" name="days_before" defaultValue={rule.days_before}/></div><div><label className="label">Horário</label><input className="field" type="time" name="send_time" defaultValue={rule.send_time?.slice(0,5)}/></div></div><button className="button-ghost mt-4">Salvar regra</button></form>}
function Status({value}:{value:string}){const color=value==="sent"?"bg-emerald-50 text-emerald-700":value==="failed"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700";return <span className={`h-fit rounded-full px-2.5 py-1 text-xs font-bold ${color}`}>{value}</span>}
