import Link from "next/link";
import { ArrowLeft, Save } from "lucide-react";
import { createClientRecord, updateClientRecord } from "@/app/(crm)/actions";

type Source={id:string;name:string};
type Client={id:string;name:string;tax_id:string|null;phone:string|null;email:string|null;city:string|null;state:string|null;notes:string|null;lead_source_id:string|null};
export function ClientForm({error,sources=[],client}:{error?:string;sources?:Source[];client?:Client}){
  const action=client?updateClientRecord:createClientRecord;
  return <div className="mx-auto max-w-4xl"><Link href={client?`/clientes/${client.id}`:"/clientes"} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-ink/55"><ArrowLeft className="h-4 w-4"/>Voltar</Link><div className="card p-6 lg:p-8"><h1 className="text-3xl font-black">{client?"Editar cliente":"Novo cliente"}</h1><p className="mt-1 text-sm text-ink/50">Informações comerciais, contato e origem do relacionamento.</p>{error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form action={action} className="mt-8 grid gap-5 sm:grid-cols-2">{client&&<input type="hidden" name="id" value={client.id}/>}<Field name="name" label="Nome / Razão social" required value={client?.name}/><Field name="tax_id" label="CPF / CNPJ" value={client?.tax_id}/><Field name="phone" label="Telefone / WhatsApp" value={client?.phone}/><Field name="email" label="E-mail" type="email" value={client?.email}/><div><label className="label">Origem do lead</label><select className="field" name="lead_source_id" defaultValue={client?.lead_source_id??""}><option value="">Não informado</option>{sources.map(source=><option value={source.id} key={source.id}>{source.name}</option>)}</select></div><Field name="city" label="Cidade" value={client?.city}/><Field name="state" label="Estado" value={client?.state}/><div className="sm:col-span-2"><label className="label">Observações</label><textarea className="field min-h-28" name="notes" defaultValue={client?.notes??""}/></div><div className="flex justify-end gap-3 sm:col-span-2"><Link href={client?`/clientes/${client.id}`:"/clientes"} className="button-ghost">Cancelar</Link><button className="button"><Save className="h-4 w-4"/>Salvar cliente</button></div></form></div></div>}
function Field({name,label,type="text",required,value}:{name:string;label:string;type?:string;required?:boolean;value?:string|null}){return <div><label className="label">{label}</label><input className="field" name={name} type={type} required={required} defaultValue={value??""}/></div>}
