import Link from "next/link";
import { ArrowLeft, CalendarClock, Check, Circle, MapPin, Play, UserRound } from "lucide-react";
import { updateInstallationChecklist, updateInstallationStatus } from "@/app/(crm)/actions";
import { createClient } from "@/lib/supabase/server";
import { shortDate } from "@/lib/utils";

type Checklist={id:string;title:string;completed:boolean;completed_at:string|null;notes:string|null;sort_order:number;required:boolean;completed_by_profile?:{full_name?:string}|null};
export async function InstallationChecklistPage({id,error,saved}:{id:string;error?:string;saved?:boolean}){
  const db=await createClient();const installationResult=await db.from("installations").select("id,status,scheduled_at,address,notes,completed_at,order:orders(order_number,client:clients(name,phone,whatsapp,address,neighborhood,city,state)),responsible:profiles(full_name)").eq("id",id).single();
  if(installationResult.error||!installationResult.data)return <div className="card p-8">Instalação não encontrada: {installationResult.error?.message}</div>;
  const installation=installationResult.data as unknown as Record<string,unknown>;const order=installation.order as Record<string,unknown>;const client=order?.client as Record<string,unknown>;const responsible=installation.responsible as {full_name?:string}|null;
  const checklistResult=await db.from("installation_checklists").select("id,title,completed,completed_at,notes,sort_order,required,completed_by_profile:profiles!installation_checklists_completed_by_fkey(full_name)").eq("installation_id",id).order("sort_order");const items=(checklistResult.data as unknown as Checklist[])??[];const done=items.filter(x=>x.completed).length;const percent=items.length?Math.round(done/items.length*100):0;
  return <div className="mx-auto max-w-4xl"><div className="mb-5 flex items-center justify-between"><Link href="/instalacoes" className="inline-flex items-center gap-2 text-sm font-bold text-ink/55"><ArrowLeft className="h-4 w-4"/>Voltar</Link><Status value={String(installation.status)}/></div>
    {(error||checklistResult.error)&&<p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error||checklistResult.error?.message}</p>}{saved&&<p className="mb-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">Etapa atualizada.</p>}
    <section className="card overflow-hidden"><div className="bg-ink p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-lime">Instalação em campo</p><h1 className="mt-2 text-2xl font-black">{String(order?.order_number||"Pedido")}</h1><p className="mt-1 text-lg font-bold">{String(client?.name||"Cliente não informado")}</p><div className="mt-4 grid gap-2 text-xs text-white/65 sm:grid-cols-3"><p className="flex gap-2"><MapPin className="h-4 w-4 text-lime"/>{String(installation.address||[client?.address,client?.neighborhood,client?.city].filter(Boolean).join(" · ")||"Endereço não informado")}</p><p className="flex gap-2"><CalendarClock className="h-4 w-4 text-lime"/>{shortDate(installation.scheduled_at as string)}</p><p className="flex gap-2"><UserRound className="h-4 w-4 text-lime"/>{responsible?.full_name||"Sem responsável"}</p></div></div><div className="p-5"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-ink/40">Progresso</p><p className="mt-1 text-2xl font-black">{done} de {items.length}</p></div><b className="text-2xl text-forest">{percent}%</b></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-cream"><div className="h-full rounded-full bg-lime transition-all" style={{width:`${percent}%`}}/></div>{!["em_andamento","concluida"].includes(String(installation.status))&&<form action={updateInstallationStatus} className="mt-4"><input type="hidden" name="installation_id" value={id}/><input type="hidden" name="status" value="em_andamento"/><button className="button w-full py-3"><Play className="h-4 w-4"/>Iniciar instalação</button></form>}</div></section>
    <section className="mt-5 space-y-3">{items.map((item,index)=><form action={updateInstallationChecklist} className={`card p-4 transition ${item.completed?"border-emerald-200 bg-emerald-50/30":""}`} key={item.id}><input type="hidden" name="item_id" value={item.id}/><input type="hidden" name="installation_id" value={id}/><div className="flex items-start gap-4"><label className="relative mt-0.5 block cursor-pointer"><input className="peer sr-only" type="checkbox" name="completed" defaultChecked={item.completed}/><span className="flex h-11 w-11 items-center justify-center rounded-full border-2 bg-white text-transparent peer-checked:border-forest peer-checked:bg-forest peer-checked:text-white"><Check className="h-5 w-5"/></span></label><div className="min-w-0 flex-1"><div className="flex gap-2"><span className="text-xs font-black text-ink/30">{String(index+1).padStart(2,"0")}</span><h2 className={`font-black ${item.completed?"text-emerald-800":""}`}>{item.title}</h2></div><textarea className="field mt-3 min-h-20 text-sm" name="notes" defaultValue={item.notes??""} placeholder="Observações, medidas, ocorrências..."/>{item.completed&&<p className="mt-2 text-xs text-emerald-700">Concluído {item.completed_at?`em ${shortDate(item.completed_at)}`:""}{item.completed_by_profile?.full_name?` por ${item.completed_by_profile.full_name}`:""}</p>}<button className="button-ghost mt-3 w-full sm:w-auto">Salvar etapa</button></div></div></form>)}{!items.length&&<div className="card p-8 text-center"><Circle className="mx-auto text-ink/20"/><p className="mt-3 font-bold">Checklist ainda não criado.</p><p className="text-sm text-ink/45">Execute a migração 008 para gerar os itens padrão.</p></div>}</section>
    {items.length>0&&percent===100&&<div className="sticky bottom-4 mt-5 rounded-2xl bg-emerald-600 p-4 text-center font-black text-white shadow-soft">Instalação concluída e pós-venda iniciado automaticamente.</div>}
  </div>;
}
function Status({value}:{value:string}){const completed=value==="concluida";return <span className={`rounded-full px-3 py-1.5 text-xs font-bold ${completed?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{value.replaceAll("_"," ")}</span>}
