import Link from "next/link";
import { ArrowLeft, Plus, Save } from "lucide-react";
import { saveLeadSource } from "@/app/(crm)/actions";
import { createClient } from "@/lib/supabase/server";

type Source={id:string;name:string;channel:string;active:boolean;sort_order:number};
const channels=["busca","social","indicação","parceiro","telefone","mensagem","relacionamento","presencial","site","marketplace","outros"];
export async function LeadSourcesPage({error,saved}:{error?:string;saved?:boolean}){
  let sources:Source[]=[];let loadError="";let canManage=false;if(process.env.NEXT_PUBLIC_SUPABASE_URL){const db=await createClient();const [permission,result]=await Promise.all([db.rpc("has_table_access",{resource:"lead_sources",action:"update"}),db.from("lead_sources").select("id,name,channel,active,sort_order").order("sort_order").order("name")]);canManage=Boolean(permission.data);sources=(result.data as Source[])??[];loadError=result.error?.message??"";}
  return <div className="mx-auto max-w-4xl"><Link href="/configuracoes" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-ink/55"><ArrowLeft className="h-4 w-4"/>Voltar</Link><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.22em] text-forest">Marketing e comercial</p><h1 className="mt-2 text-3xl font-black">Origens de lead</h1><p className="mt-1 text-sm text-ink/50">Configure por onde os clientes conhecem a empresa.</p></div>{(error||loadError)&&<p className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error||loadError}</p>}{saved&&<p className="mb-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">Origem salva.</p>}
    {canManage&&<details className="card mb-5"><summary className="flex cursor-pointer list-none items-center gap-2 p-5 font-black"><Plus className="h-4 w-4"/>Nova origem</summary><SourceForm/></details>}
    <div className="space-y-3">{sources.map(source=><form action={saveLeadSource} className="card grid items-end gap-3 p-4 sm:grid-cols-[1.5fr_1fr_.45fr_.4fr_auto]" key={source.id}><input type="hidden" name="id" value={source.id}/><div><label className="label">Nome</label><input className="field" name="name" defaultValue={source.name} disabled={!canManage}/></div><div><label className="label">Canal</label><select className="field" name="channel" defaultValue={source.channel} disabled={!canManage}>{channels.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Ordem</label><input className="field" type="number" name="sort_order" defaultValue={source.sort_order} disabled={!canManage}/></div><label className="flex items-center gap-2 pb-3 text-xs font-bold"><input type="checkbox" name="active" defaultChecked={source.active} disabled={!canManage}/>Ativa</label>{canManage&&<button className="button-ghost p-2.5"><Save className="h-4 w-4"/></button>}</form>)}{!sources.length&&<div className="card p-8 text-center text-sm text-ink/45">Execute a migração 010 para criar Google, Meta, Indicação, Arquiteto, Engenheiro e outras opções.</div>}</div>
  </div>;
}
function SourceForm(){return <form action={saveLeadSource} className="grid gap-4 border-t p-5 sm:grid-cols-2"><div><label className="label">Nome</label><input className="field" name="name" placeholder="Ex.: Feira ou evento" required/></div><div><label className="label">Canal</label><select className="field" name="channel">{channels.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Ordem</label><input className="field" type="number" name="sort_order" defaultValue="500"/></div><label className="flex items-center gap-2 self-end pb-3 text-sm font-bold"><input type="checkbox" name="active" defaultChecked/>Origem ativa</label><button className="button sm:col-span-2"><Save className="h-4 w-4"/>Salvar origem</button></form>}
