"use client";

import Link from "next/link";
import { ArrowLeft, Plus, Save, Trash2 } from "lucide-react";
import { createManualPurchase } from "@/app/(crm)/actions";
import { money } from "@/lib/utils";
import { useMemo, useState } from "react";
import type { ReactElement } from "react";

type Supplier={id:string;name:string};type Material={id:string;name:string;unit:string};type Item={material_id:string;description:string;category:string;unit:string;quantity:number;unit_price:number;notes:string};
const categories=["Perfis de alumínio","Parafusos","Silicone","PU","Borrachas","Acessórios","Ferramentas","Tintas e pintura","Vidros","Chapas de calha","Bobinas","Ferragens","Embalagens","Motores","Outros"];
const blank=():Item=>({material_id:"",description:"",category:"Outros",unit:"un",quantity:1,unit_price:0,notes:""});
export function ManualPurchaseForm({suppliers,materials,error}:{suppliers:Supplier[];materials:Material[];error?:string}){
  const [items,setItems]=useState<Item[]>([blank()]);const [supplierId,setSupplierId]=useState("");const [expected,setExpected]=useState("");const [paid,setPaid]=useState(0);const [method,setMethod]=useState("Pix");const [notes,setNotes]=useState("");const total=useMemo(()=>items.reduce((sum,x)=>sum+x.quantity*x.unit_price,0),[items]);const payload=JSON.stringify({supplier_id:supplierId,expected_at:expected,paid_amount:paid,paid_at:new Date().toISOString().slice(0,10),payment_method:method,notes,items});
  const update=(index:number,key:keyof Item,value:string)=>setItems(current=>current.map((x,i)=>{if(i!==index)return x;const next={...x,[key]:["quantity","unit_price"].includes(key)?Number(value):value} as Item;if(key==="material_id"&&value){const material=materials.find(m=>m.id===value);if(material){next.description=material.name;next.unit=material.unit}}return next}));
  return <div className="mx-auto max-w-6xl"><Link href="/compras" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-ink/55"><ArrowLeft className="h-4 w-4"/>Voltar</Link><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.22em] text-forest">Lançamento manual</p><h1 className="mt-2 text-3xl font-black">Nova compra</h1><p className="mt-1 text-sm text-ink/50">Perfis, parafusos, vedantes, tintas, borrachas, acessórios, ferramentas e outros materiais.</p></div>{error&&<p className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <form action={createManualPurchase} className="grid gap-5 xl:grid-cols-[1fr_330px]"><input type="hidden" name="payload" value={payload}/><div className="space-y-4"><div className="card p-5"><label className="label">Fornecedor</label><select className="field" value={supplierId} onChange={e=>setSupplierId(e.target.value)} required><option value="">Selecione</option>{suppliers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div>{items.map((item,index)=><div className="card p-5" key={index}><div className="mb-4 flex justify-between"><b>Item {index+1}</b><button type="button" disabled={items.length===1} className="button-ghost p-2 text-red-600" onClick={()=>setItems(x=>x.filter((_,i)=>i!==index))}><Trash2 className="h-4 w-4"/></button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="sm:col-span-2"><label className="label">Material existente (opcional)</label><select className="field" value={item.material_id} onChange={e=>update(index,"material_id",e.target.value)}><option value="">Cadastrar pelo nome abaixo</option>{materials.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><Field label="Descrição do material" value={item.description} onChange={v=>update(index,"description",v)}/><div><label className="label">Categoria</label><select className="field" value={item.category} onChange={e=>update(index,"category",e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></div><Field label="Unidade" value={item.unit} onChange={v=>update(index,"unit",v)}/><Number label="Quantidade" value={item.quantity} onChange={v=>update(index,"quantity",v)}/><Number label="Valor unitário" value={item.unit_price} onChange={v=>update(index,"unit_price",v)}/><Field label="Observação" value={item.notes} onChange={v=>update(index,"notes",v)}/></div><p className="mt-3 text-right font-black">{money(item.quantity*item.unit_price)}</p></div>)}<button type="button" className="button-ghost w-full border-dashed" onClick={()=>setItems(x=>[...x,blank()])}><Plus className="h-4 w-4"/>Adicionar item</button></div>
      <aside className="card h-fit p-5 xl:sticky xl:top-24"><h2 className="font-black">Resumo da compra</h2><p className="mt-4 text-3xl font-black text-forest">{money(total)}</p><div className="mt-5 space-y-4"><Number label="Valor já pago" value={paid} onChange={v=>setPaid(Number(v))}/><div><label className="label">Previsão de chegada</label><input className="field" type="date" value={expected} onChange={e=>setExpected(e.target.value)}/></div><div><label className="label">Forma de pagamento</label><select className="field" value={method} onChange={e=>setMethod(e.target.value)}>{["Pix","Dinheiro","Cartão de crédito","Boleto","Transferência","Prazo com fornecedor","Outro"].map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Observações</label><textarea className="field min-h-24" value={notes} onChange={e=>setNotes(e.target.value)}/></div><button disabled={!supplierId||total<=0||paid>total||items.some(x=>!x.description)} className="button w-full"><Save className="h-4 w-4"/>Cadastrar compra</button></div></aside></form>
  </div>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><label className="label">{label}</label><input className="field" value={value} onChange={e=>onChange(e.target.value)} required/></div>}
function Number(value:string):number;
function Number(props:{label:string;value:number;onChange:(v:string)=>void}):ReactElement;
function Number(input:string|{label:string;value:number;onChange:(v:string)=>void}){if(typeof input==="string")return globalThis.Number(input);const{label,value,onChange}=input;return <div><label className="label">{label}</label><input className="field" type="number" min="0" step="0.001" value={value} onChange={e=>onChange(e.target.value)} required/></div>}
