"use client";

import Link from "next/link";
import { ArrowLeft, Plus, Save, Trash2 } from "lucide-react";
import { createManualSale } from "@/app/(crm)/actions";
import { money } from "@/lib/utils";
import { useMemo, useState } from "react";
import type { ReactElement } from "react";

type Option={id:string;name:string};type Item={product:string;description:string;unit:string;quantity:number;unit_price:number;requires_purchase:boolean;requires_production:boolean};
const blank=():Item=>({product:"",description:"",unit:"un",quantity:1,unit_price:0,requires_purchase:false,requires_production:false});
export function ManualSaleForm({clients,saleTypes,error}:{clients:Option[];saleTypes:Option[];error?:string}){
  const [items,setItems]=useState<Item[]>([blank()]);const [clientId,setClientId]=useState("");const [saleTypeId,setSaleTypeId]=useState("");const [paid,setPaid]=useState(0);const [due,setDue]=useState(new Date().toISOString().slice(0,10));const [method,setMethod]=useState("Pix");const [notes,setNotes]=useState("");
  const total=useMemo(()=>items.reduce((sum,x)=>sum+x.quantity*x.unit_price,0),[items]);const payload=JSON.stringify({client_id:clientId,sale_type_id:saleTypeId,paid_amount:paid,due_date:due,paid_at:new Date().toISOString().slice(0,10),payment_method:method,notes,items});
  const update=(index:number,key:keyof Item,value:string|boolean)=>setItems(current=>current.map((x,i)=>i===index?{...x,[key]:["quantity","unit_price"].includes(key)?Number(value):value}:x));
  return <div className="mx-auto max-w-6xl"><Link href="/vendas" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-ink/55"><ArrowLeft className="h-4 w-4"/>Voltar</Link><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.22em] text-forest">Lançamento manual</p><h1 className="mt-2 text-3xl font-black">Nova venda avulsa</h1><p className="mt-1 text-sm text-ink/50">Registra venda, itens, saldo e pagamento inicial em uma única operação.</p></div>{error&&<p className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <form action={createManualSale} className="grid gap-5 xl:grid-cols-[1fr_330px]"><input type="hidden" name="payload" value={payload}/><div className="space-y-4"><div className="card grid gap-4 p-5 sm:grid-cols-2"><Select label="Cliente" value={clientId} onChange={setClientId} options={clients}/><Select label="Tipo de venda" value={saleTypeId} onChange={setSaleTypeId} options={saleTypes}/></div>{items.map((item,index)=><div className="card p-5" key={index}><div className="mb-4 flex justify-between"><b>Item {index+1}</b><button type="button" disabled={items.length===1} className="button-ghost p-2 text-red-600" onClick={()=>setItems(x=>x.filter((_,i)=>i!==index))}><Trash2 className="h-4 w-4"/></button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Produto / serviço" value={item.product} onChange={v=>update(index,"product",v)}/><Field label="Descrição" value={item.description} onChange={v=>update(index,"description",v)}/><Field label="Unidade" value={item.unit} onChange={v=>update(index,"unit",v)}/><Number label="Quantidade" value={item.quantity} onChange={v=>update(index,"quantity",v)}/><Number label="Valor unitário" value={item.unit_price} onChange={v=>update(index,"unit_price",v)}/><label className="flex items-center gap-2 self-end pb-3 text-xs font-bold"><input type="checkbox" checked={item.requires_purchase} onChange={e=>update(index,"requires_purchase",e.target.checked)}/>Exige compra</label><label className="flex items-center gap-2 self-end pb-3 text-xs font-bold"><input type="checkbox" checked={item.requires_production} onChange={e=>update(index,"requires_production",e.target.checked)}/>Exige produção</label><p className="self-end pb-3 text-right font-black">{money(item.quantity*item.unit_price)}</p></div></div>)}<button type="button" className="button-ghost w-full border-dashed" onClick={()=>setItems(x=>[...x,blank()])}><Plus className="h-4 w-4"/>Adicionar item</button></div>
      <aside className="card h-fit p-5 xl:sticky xl:top-24"><h2 className="font-black">Financeiro</h2><p className="mt-4 text-3xl font-black text-forest">{money(total)}</p><div className="mt-5 space-y-4"><Number label="Valor já recebido" value={paid} onChange={v=>setPaid(Number(v))}/><div><label className="label">Vencimento do saldo</label><input className="field" type="date" value={due} onChange={e=>setDue(e.target.value)}/></div><div><label className="label">Forma de pagamento</label><select className="field" value={method} onChange={e=>setMethod(e.target.value)}>{["Pix","Dinheiro","Cartão de crédito","Cartão de débito","Boleto","Transferência","Outro"].map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Observações</label><textarea className="field min-h-24" value={notes} onChange={e=>setNotes(e.target.value)}/></div><button disabled={!clientId||!saleTypeId||total<=0||paid>total||items.some(x=>!x.product)} className="button w-full"><Save className="h-4 w-4"/>Cadastrar venda</button></div></aside></form>
  </div>;
}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Option[]}){return <div><label className="label">{label}</label><select className="field" value={value} onChange={e=>onChange(e.target.value)} required><option value="">Selecione</option>{options.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><label className="label">{label}</label><input className="field" value={value} onChange={e=>onChange(e.target.value)} required/></div>}
function Number(value:string|boolean):number;
function Number(props:{label:string;value:number;onChange:(v:string)=>void}):ReactElement;
function Number(input:string|boolean|{label:string;value:number;onChange:(v:string)=>void}){if(typeof input!=="object")return globalThis.Number(input);const{label,value,onChange}=input;return <div><label className="label">{label}</label><input className="field" type="number" min="0" step="0.01" value={value} onChange={e=>onChange(e.target.value)} required/></div>}
