import { CheckCircle2, Clock3, PackageCheck, PackageOpen, Truck } from "lucide-react";
import { receivePurchaseItem } from "@/app/(crm)/actions";
import { createClient } from "@/lib/supabase/server";
import { shortDate } from "@/lib/utils";

type Material={id:string;order_number:string|null;client_name:string|null;sale_type:string|null;product:string|null;material_name:string; supplier_name:string|null;ordered_at:string|null;expected_at:string|null;received_at:string|null;purchase_status:string; purchased_quantity:number;received_quantity:number;pending_quantity:number;material_status:string;released_for_production:boolean;notes:string|null};
type Location={id:string;name:string};
export async function OrderMaterialsPage({error,received}:{error?:string;received?:boolean}){
  let materials:Material[]=[];let locations:Location[]=[];let loadError="";
  if(process.env.NEXT_PUBLIC_SUPABASE_URL){const db=await createClient();const [items,stocks]=await Promise.all([db.from("v_order_materials").select("*").order("expected_at",{ascending:true}),db.from("stock_locations").select("id,name").eq("active",true).order("name")]);materials=(items.data as Material[])??[];locations=(stocks.data as Location[])??[];loadError=items.error?.message||stocks.error?.message||"";}
  const pending=materials.filter(x=>Number(x.pending_quantity)>0).length;const complete=materials.length-pending;
  return <div className="mx-auto max-w-[1500px]"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.22em] text-forest">Produção sem WhatsApp</p><h1 className="mt-2 text-3xl font-black">Materiais do pedido</h1><p className="mt-1 text-sm text-ink/50">{complete} completos · {pending} aguardando recebimento</p></div>
    {(error||loadError)&&<p className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error||loadError}</p>}{received&&<p className="mb-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">Material recebido, estoque e produção atualizados.</p>}{!locations.length&&<p className="mb-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Cadastre um local de estoque antes de receber materiais.</p>}
    <section className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{materials.map(item=><article className="card overflow-hidden" key={item.id}><div className="flex items-start justify-between gap-4 border-b p-5"><div><p className="text-xs font-bold text-forest">{item.order_number||"Sem pedido"}</p><h2 className="mt-1 text-lg font-black">{item.client_name||"Cliente não informado"}</h2><p className="text-xs text-ink/45">{item.sale_type||item.product||"-"}</p></div><Status pending={Number(item.pending_quantity)} status={item.material_status}/></div><div className="p-5"><h3 className="font-black">{item.material_name}</h3><p className="mt-1 text-xs text-ink/45">Fornecedor: {item.supplier_name||"Não definido"}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Metric label="Comprado" value={item.purchased_quantity}/><Metric label="Recebido" value={item.received_quantity}/><Metric label="Pendente" value={item.pending_quantity} alert={Number(item.pending_quantity)>0}/></div><div className="mt-4 flex justify-between text-xs text-ink/45"><span className="flex items-center gap-1"><Truck className="h-3.5 w-3.5"/>Previsão: {shortDate(item.expected_at)}</span><span className="flex items-center gap-1"><PackageCheck className="h-3.5 w-3.5"/>{item.released_for_production?"Liberado":"Não liberado"}</span></div>{item.notes&&<p className="mt-3 rounded-lg bg-cream/70 p-3 text-xs text-ink/60">{item.notes}</p>}
        {Number(item.pending_quantity)>0&&<details className="mt-4"><summary className="button w-full cursor-pointer list-none"><PackageOpen className="h-4 w-4"/>Receber material</summary><form action={receivePurchaseItem} className="mt-3 grid gap-3 rounded-xl bg-cream/60 p-4 sm:grid-cols-2"><input type="hidden" name="item_id" value={item.id}/><div><label className="label">Quantidade recebida</label><input className="field" type="number" name="quantity" min="0.001" max={Number(item.pending_quantity)} step="0.001" defaultValue={Number(item.pending_quantity)} required/></div><div><label className="label">Local de estoque</label><select className="field" name="location_id" required>{locations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><div className="sm:col-span-2"><label className="label">Observação do recebimento</label><input className="field" name="notes" placeholder="Nota, avaria, lote..."/></div><button disabled={!locations.length} className="button sm:col-span-2"><CheckCircle2 className="h-4 w-4"/>Confirmar entrada no estoque</button></form></details>}
      </div></article>)}{!materials.length&&<div className="card col-span-full p-12 text-center"><PackageOpen className="mx-auto h-8 w-8 text-ink/20"/><h2 className="mt-4 font-black">Nenhum material vinculado</h2><p className="mt-1 text-sm text-ink/45">Os itens de compras vinculados aos pedidos aparecerão aqui.</p></div>}</section>
  </div>;
}
function Metric({label,value,alert}:{label:string;value:number;alert?:boolean}){return <div className={`rounded-xl p-3 ${alert?"bg-orange-50 text-orange-700":"bg-cream/70"}`}><p className="text-[10px] font-bold uppercase tracking-wider opacity-50">{label}</p><p className="mt-1 font-black">{Number(value)}</p></div>}
function Status({pending,status}:{pending:number;status:string}){const complete=pending<=0;return <span className={`flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold ${complete?"bg-emerald-50 text-emerald-700":"bg-orange-50 text-orange-700"}`}>{complete?<CheckCircle2 className="h-3.5 w-3.5"/>:<Clock3 className="h-3.5 w-3.5"/>}{complete?"Recebido completo":status?.replaceAll("_"," ")||"Pendente"}</span>}
