"use client";

import { moveLeadStage } from "@/app/(crm)/actions";
import { money, shortDate } from "@/lib/utils";
import { CalendarClock, GripVertical, Phone, UserRound } from "lucide-react";
import { useState, useTransition } from "react";

export type Stage={id:string;name:string;color:string|null;sort_order:number;is_won:boolean;is_lost:boolean};
export type Lead={id:string;name:string;phone:string|null;source:string|null;stage_id:string;estimated_value:number|null;next_action:string|null;next_action_date:string|null;status:string;owner?:{full_name?:string}|null};
export function PipelineBoard({initialStages,initialLeads}:{initialStages:Stage[];initialLeads:Lead[]}){
  const [leads,setLeads]=useState(initialLeads);const [pending,startTransition]=useTransition();
  const move=(leadId:string,stageId:string)=>{const previous=leads;setLeads(items=>items.map(x=>x.id===leadId?{...x,stage_id:stageId}:x));startTransition(async()=>{try{await moveLeadStage(leadId,stageId)}catch{setLeads(previous)}})};
  return <div className={`overflow-x-auto pb-4 ${pending?"opacity-80":""}`}><div className="flex min-w-max gap-4">{initialStages.map(stage=>{const items=leads.filter(x=>x.stage_id===stage.id);const total=items.reduce((sum,x)=>sum+Number(x.estimated_value||0),0);return <section key={stage.id} className="w-[310px] rounded-2xl bg-ink/[.035] p-3" onDragOver={e=>e.preventDefault()} onDrop={e=>move(e.dataTransfer.getData("lead-id"),stage.id)}><div className="mb-3 flex items-start justify-between gap-3 px-1"><div><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:stage.color||"#94a3b8"}}/><h2 className="font-black">{stage.name}</h2><span className="rounded-full bg-white px-2 text-xs font-bold">{items.length}</span></div><p className="mt-1 text-xs text-ink/45">{money(total)}</p></div></div><div className="min-h-28 space-y-3">{items.map(lead=><article draggable onDragStart={e=>e.dataTransfer.setData("lead-id",lead.id)} className="card cursor-grab p-4 active:cursor-grabbing" key={lead.id}><div className="flex items-start gap-2"><GripVertical className="mt-0.5 h-4 w-4 shrink-0 text-ink/20"/><div className="min-w-0 flex-1"><h3 className="font-black">{lead.name}</h3><p className="mt-1 text-lg font-black text-forest">{money(lead.estimated_value)}</p></div></div><div className="mt-3 space-y-1.5 text-xs text-ink/50">{lead.phone&&<p className="flex items-center gap-2"><Phone className="h-3.5 w-3.5"/>{lead.phone}</p>}{lead.next_action&&<p className="flex items-center gap-2"><CalendarClock className="h-3.5 w-3.5"/>{lead.next_action} · {shortDate(lead.next_action_date)}</p>}<p className="flex items-center gap-2"><UserRound className="h-3.5 w-3.5"/>{lead.owner?.full_name||"Sem responsável"}</p></div><select aria-label="Mover etapa" className="field mt-3 py-1.5 text-xs" value={lead.stage_id} onChange={e=>move(lead.id,e.target.value)}>{initialStages.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></article>)}{!items.length&&<div className="rounded-xl border border-dashed p-6 text-center text-xs text-ink/35">Arraste uma oportunidade para cá</div>}</div></section>})}</div></div>;
}
