import { AlertTriangle, Banknote, CalendarRange, ChartNoAxesColumnIncreasing, CircleDollarSign, FileText, ShoppingCart, TrendingUp } from "lucide-react";
import { PrintButton } from "@/components/print-button";
import { createClient } from "@/lib/supabase/server";
import { money, shortDate } from "@/lib/utils";

type Datum={name:string;color?:string;quantity:number;total:number;sort_order?:number};
type Summary={sales_total:number;sales_count:number;average_ticket:number;received:number;paid:number;receivable:number;payable:number;overdue_receivable:number;late_purchases:number;blocked_orders:number;waiting_materials:number;quotes_open:number;sales_by_type:Datum[];quotes_by_status:Array<{status:string;quantity:number;total:number}>;pipeline_by_stage:Datum[];monthly_sales:Array<{month:string;quantity:number;total:number}>};
const empty:Summary={sales_total:0,sales_count:0,average_ticket:0,received:0,paid:0,receivable:0,payable:0,overdue_receivable:0,late_purchases:0,blocked_orders:0,waiting_materials:0,quotes_open:0,sales_by_type:[],quotes_by_status:[],pipeline_by_stage:[],monthly_sales:[]};

export async function ReportsPage({start,end}:{start?:string;end?:string}){
  const today=new Date();const from=start||new Date(today.getFullYear(),today.getMonth(),1).toISOString().slice(0,10);const to=end||today.toISOString().slice(0,10);let data=empty;let error="";
  if(process.env.NEXT_PUBLIC_SUPABASE_URL){const db=await createClient();const result=await db.rpc("reporting_summary",{p_start:from,p_end:to});data={...empty,...(result.data as Partial<Summary>)};error=result.error?.message??"";}
  const cards=[{label:"Vendas no período",value:money(data.sales_total),detail:`${data.sales_count} vendas`,icon:TrendingUp,color:"bg-emerald-50 text-emerald-700"},{label:"Recebido",value:money(data.received),detail:"Pagamentos de clientes",icon:Banknote,color:"bg-blue-50 text-blue-700"},{label:"Pago",value:money(data.paid),detail:"Pagamentos a fornecedores",icon:CircleDollarSign,color:"bg-orange-50 text-orange-700"},{label:"Ticket médio",value:money(data.average_ticket),detail:"Média por venda",icon:ChartNoAxesColumnIncreasing,color:"bg-violet-50 text-violet-700"}];
  return <div className="mx-auto max-w-[1500px]"><div className="no-print mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-forest">Indicadores reais</p><h1 className="mt-2 text-3xl font-black">Relatórios</h1><p className="mt-1 text-sm text-ink/50">Comercial, financeiro e operação em um único período.</p></div><div className="flex flex-wrap gap-3"><form className="flex gap-2 rounded-xl border bg-white p-1.5"><input aria-label="Data inicial" className="rounded-lg px-2 text-sm" type="date" name="inicio" defaultValue={from}/><input aria-label="Data final" className="rounded-lg px-2 text-sm" type="date" name="fim" defaultValue={to}/><button className="button py-2"><CalendarRange className="h-4 w-4"/>Filtrar</button></form><PrintButton label="Imprimir relatório"/></div></div>
    <div className="print-sheet"><div className="hidden print:block"><h1 className="text-2xl font-black">Relatório gerencial</h1><p className="mb-5 text-sm">Período: {shortDate(from)} a {shortDate(to)}</p></div>{error&&<p className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">Não foi possível gerar o relatório: {error}</p>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card=><div className="card p-5" key={card.label}><div className="flex items-center justify-between"><p className="text-sm font-medium text-ink/55">{card.label}</p><span className={`rounded-xl p-2.5 ${card.color}`}><card.icon className="h-5 w-5"/></span></div><p className="mt-4 text-2xl font-black">{card.value}</p><p className="mt-1 text-xs text-ink/40">{card.detail}</p></div>)}</section>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><ChartCard title="Vendas por tipo" data={data.sales_by_type}/><Monthly data={data.monthly_sales}/><ChartCard title="Pipeline por etapa" data={data.pipeline_by_stage}/><QuoteStatus data={data.quotes_by_status}/></section>
    <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Risk label="Contas vencidas" value={money(data.overdue_receivable)} icon={AlertTriangle} tone="red"/><Risk label="Compras atrasadas" value={String(data.late_purchases)} icon={ShoppingCart} tone="orange"/><Risk label="Pedidos bloqueados" value={String(data.blocked_orders)} icon={AlertTriangle} tone="red"/><Risk label="Aguardando material" value={String(data.waiting_materials)} icon={FileText} tone="amber"/></section>
    <section className="card mt-5 grid gap-6 p-6 sm:grid-cols-3"><Total label="A receber" value={money(data.receivable)}/><Total label="A pagar" value={money(data.payable)}/><Total label="Saldo previsto" value={money(data.receivable-data.payable)} accent/></section></div>
  </div>;
}
function ChartCard({title,data}:{title:string;data:Datum[]}){const rows=(data||[]).filter(x=>x&&x.name);const max=Math.max(1,...rows.map(x=>Number(x.total)));return <div className="card p-5"><h2 className="font-black">{title}</h2><div className="mt-5 space-y-4">{rows.length?rows.map(x=><div key={x.name}><div className="mb-1.5 flex justify-between text-xs"><span className="font-bold">{x.name}</span><span>{x.quantity} · {money(x.total)}</span></div><div className="h-2 rounded-full bg-cream"><div className="h-full rounded-full bg-forest" style={{width:`${Math.max(3,Number(x.total)/max*100)}%`,backgroundColor:x.color||undefined}}/></div></div>):<Empty/>}</div></div>}
function Monthly({data}:{data:Summary["monthly_sales"]}){const rows=(data||[]).filter(x=>x&&x.month);const max=Math.max(1,...rows.map(x=>Number(x.total)));return <div className="card p-5"><h2 className="font-black">Evolução mensal</h2><div className="mt-5 flex h-44 items-end gap-3">{rows.length?rows.map(x=>{const d=new Date(`${String(x.month).slice(0,7)}-01T12:00:00`);const label=Number.isNaN(d.getTime())?"?":new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(d);return <div className="flex h-full flex-1 flex-col justify-end text-center" key={x.month}><span className="mb-2 text-[10px] font-bold">{money(x.total)}</span><div className="mx-auto w-full max-w-14 rounded-t-lg bg-lime" style={{height:`${Math.max(5,Number(x.total)/max*120)}px`}}/><span className="mt-2 text-[10px] text-ink/45">{label}</span></div>;}):<Empty/>}</div></div>}
function QuoteStatus({data}:{data:Summary["quotes_by_status"]}){const rows=(data||[]).filter(x=>x&&x.status);return <div className="card p-5"><h2 className="font-black">Orçamentos por status</h2><div className="mt-4 divide-y">{rows.length?rows.map(x=><div className="flex justify-between py-3 text-sm" key={x.status}><span className="font-bold capitalize">{String(x.status).replaceAll("_"," ")}</span><span>{x.quantity} · {money(x.total)}</span></div>):<Empty/>}</div></div>}
function Risk({label,value,icon:Icon,tone}:{label:string;value:string;icon:typeof AlertTriangle;tone:string}){const colors:Record<string,string>={red:"bg-red-50 text-red-700",orange:"bg-orange-50 text-orange-700",amber:"bg-amber-50 text-amber-700"};return <div className="card flex items-center gap-3 p-4"><span className={`rounded-xl p-2.5 ${colors[tone]}`}><Icon className="h-5 w-5"/></span><div><p className="text-xs text-ink/45">{label}</p><p className="font-black">{value}</p></div></div>}
function Total({label,value,accent}:{label:string;value:string;accent?:boolean}){return <div><p className="text-xs font-bold uppercase tracking-wider text-ink/40">{label}</p><p className={`mt-1 text-2xl font-black ${accent?"text-forest":""}`}>{value}</p></div>}
function Empty(){return <p className="py-8 text-center text-sm text-ink/35">Sem dados no período.</p>}
