import { Boxes, Building2, CalendarCheck, CircleDollarSign, ClipboardCheck, Factory, FileText, HandCoins, PackageSearch, ShoppingCart, Users } from "lucide-react";

export type ModuleConfig = {
  title: string; singular: string; description: string; table: string; select: string; search: string[]; icon: typeof Users; create?: string;
  columns: { key: string; label: string; kind?: "money" | "date" | "status" }[];
};

export const modules: Record<string, ModuleConfig> = {
  clientes: { title: "Clientes", singular: "cliente", description: "Cadastro, contatos, vendas e pendências financeiras.", table: "clients", select: "id,name,phone,email,city,state,status,created_at", search: ["name","phone","email","tax_id"], icon: Users, create: "/clientes/novo", columns: [{key:"name",label:"Cliente"},{key:"phone",label:"Telefone"},{key:"city",label:"Cidade"},{key:"status",label:"Status",kind:"status"},{key:"created_at",label:"Cadastro",kind:"date"}] },
  orcamentos: { title: "Orçamentos", singular: "orçamento", description: "Propostas em elaboração, enviadas e aprovadas.", table: "quotes", select: "id,quote_number,client:clients(name),sale_type:sale_types(name),total,status,valid_until,created_at", search: ["quote_number"], icon: FileText, create: "/orcamentos/calhas", columns: [{key:"quote_number",label:"Número"},{key:"client.name",label:"Cliente"},{key:"sale_type.name",label:"Tipo"},{key:"total",label:"Total",kind:"money"},{key:"status",label:"Status",kind:"status"},{key:"valid_until",label:"Validade",kind:"date"}] },
  vendas: { title: "Vendas", singular: "venda", description: "Vendas aprovadas e evolução comercial.", table: "sales", select: "id,sale_number,client:clients(name),sale_type:sale_types(name),total,paid_amount,open_amount,financial_status,operational_status", search: ["sale_number"], icon: HandCoins, create: "/vendas/nova", columns: [{key:"sale_number",label:"Venda"},{key:"client.name",label:"Cliente"},{key:"total",label:"Total",kind:"money"},{key:"paid_amount",label:"Pago",kind:"money"},{key:"open_amount",label:"Em aberto",kind:"money"},{key:"financial_status",label:"Financeiro",kind:"status"}] },
  pedidos: { title: "Pedidos", singular: "pedido", description: "Situação comercial, financeira e operacional em um só lugar.", table: "v_order_overview", select: "*", search: ["order_number","client_name"], icon: ClipboardCheck, columns: [{key:"order_number",label:"Pedido"},{key:"client_name",label:"Cliente"},{key:"sale_type",label:"Tipo"},{key:"financial_status",label:"Financeiro",kind:"status"},{key:"operational_status",label:"Operação",kind:"status"},{key:"next_action",label:"Próxima ação"}] },
  compras: { title: "Compras", singular: "compra", description: "Solicitações, pedidos aos fornecedores e recebimentos.", table: "purchase_orders", select: "id,order_number,supplier:suppliers(name),total,paid_amount,open_amount,status,expected_at", search: ["order_number"], icon: ShoppingCart, create: "/compras/nova", columns: [{key:"order_number",label:"Compra"},{key:"supplier.name",label:"Fornecedor"},{key:"total",label:"Total",kind:"money"},{key:"open_amount",label:"Em aberto",kind:"money"},{key:"status",label:"Status",kind:"status"},{key:"expected_at",label:"Previsão",kind:"date"}] },
  fornecedores: { title: "Fornecedores", singular: "fornecedor", description: "Compras, materiais e posição financeira por fornecedor.", table: "v_supplier_summary", select: "*", search: ["name","tax_id"], icon: Building2, columns: [{key:"name",label:"Fornecedor"},{key:"category",label:"Categoria"},{key:"total_purchased",label:"Comprado",kind:"money"},{key:"total_paid",label:"Pago",kind:"money"},{key:"total_open",label:"Em aberto",kind:"money"},{key:"late_count",label:"Vencidas"}] },
  estoque: { title: "Estoque", singular: "material", description: "Saldos por local e rastreabilidade das movimentações.", table: "v_stock_balance", select: "*", search: ["name","sku"], icon: Boxes, columns: [{key:"sku",label:"Código"},{key:"name",label:"Material"},{key:"category",label:"Categoria"},{key:"location",label:"Local"},{key:"balance",label:"Saldo"},{key:"unit",label:"Unidade"}] },
  producao: { title: "Produção", singular: "ordem de produção", description: "Ordens em fila, execução e conferência.", table: "production_orders", select: "id,production_number,order:orders(order_number),status,planned_start,planned_end,started_at,finished_at", search: ["production_number"], icon: Factory, columns: [{key:"production_number",label:"Ordem"},{key:"order.order_number",label:"Pedido"},{key:"status",label:"Status",kind:"status"},{key:"planned_start",label:"Início previsto",kind:"date"},{key:"planned_end",label:"Fim previsto",kind:"date"}] },
  instalacoes: { title: "Instalações", singular: "instalação", description: "Agenda, equipes e conferência final.", table: "installations", select: "id,order:orders(order_number),scheduled_at,status,address,responsible:profiles(full_name),completed_at", search: ["address"], icon: CalendarCheck, columns: [{key:"order.order_number",label:"Pedido"},{key:"scheduled_at",label:"Agendada",kind:"date"},{key:"address",label:"Endereço"},{key:"responsible.full_name",label:"Responsável"},{key:"status",label:"Status",kind:"status"}] },
  financeiro: { title: "Financeiro", singular: "lançamento", description: "Contas a receber, contas a pagar e pagamentos parciais.", table: "financial_entries", select: "id,description,entry_type,client:clients(name),supplier:suppliers(name),total_amount,paid_amount,open_amount,due_date,status", search: ["description"], icon: CircleDollarSign, columns: [{key:"description",label:"Descrição"},{key:"entry_type",label:"Tipo",kind:"status"},{key:"client.name",label:"Cliente"},{key:"supplier.name",label:"Fornecedor"},{key:"total_amount",label:"Total",kind:"money"},{key:"open_amount",label:"Em aberto",kind:"money"},{key:"due_date",label:"Vencimento",kind:"date"},{key:"status",label:"Status",kind:"status"}] },
  materiais: { title: "Materiais do pedido", singular: "material", description: "O que chegou, o que falta e quais pedidos podem produzir.", table: "v_order_materials", select: "*", search: ["client_name","order_number","material_name"], icon: PackageSearch, columns: [{key:"order_number",label:"Pedido"},{key:"client_name",label:"Cliente"},{key:"material_name",label:"Material"},{key:"supplier_name",label:"Fornecedor"},{key:"purchased_quantity",label:"Comprado"},{key:"received_quantity",label:"Recebido"},{key:"pending_quantity",label:"Pendente"},{key:"material_status",label:"Status",kind:"status"}] },
};
