-- CRM Bielenki: schema multiempresa. Execute com Supabase CLI ou no SQL Editor.
create extension if not exists pgcrypto;

create type public.app_role as enum ('administrador','gerente','vendedor','compras','producao','estoque','instalador','financeiro','atendente');
create type public.record_status as enum ('ativo','inativo');
create type public.financial_entry_type as enum ('receber','pagar');
create type public.financial_status as enum ('aguardando_pagamento','parcialmente_pago','pago','vencido','cancelado');
create type public.checklist_status as enum ('pendente','em_andamento','concluido','bloqueado');

create table public.companies (id uuid primary key default gen_random_uuid(), name text not null, tax_id text, phone text, email text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, company_id uuid not null references public.companies(id), full_name text not null, phone text, avatar_url text, status public.record_status not null default 'ativo', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_roles (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), profile_id uuid not null references public.profiles(id) on delete cascade, role public.app_role not null, unique(profile_id,role));
create table public.permissions (id uuid primary key default gen_random_uuid(), role public.app_role not null, resource text not null, can_view boolean not null default false, can_create boolean not null default false, can_update boolean not null default false, can_delete boolean not null default false, unique(role,resource));

create table public.client_types (id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id), name text not null, active boolean not null default true, unique(company_id,name));
create table public.clients (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), client_type_id uuid references public.client_types(id), name text not null, phone text, whatsapp text, email text, tax_id text, address text, neighborhood text, city text, state char(2), lead_source text, notes text, status public.record_status not null default 'ativo', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index clients_search_idx on public.clients(company_id,name,phone);

create table public.sale_types (id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id), name text not null, requires_purchase boolean not null default false, requires_production boolean not null default false, requires_installation boolean not null default false, active boolean not null default true, unique(company_id,name));
create table public.sales (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), sale_number text not null, client_id uuid not null references public.clients(id), sale_type_id uuid not null references public.sale_types(id), seller_id uuid references public.profiles(id), total numeric(14,2) not null default 0 check(total>=0), paid_amount numeric(14,2) not null default 0 check(paid_amount>=0), open_amount numeric(14,2) generated always as (greatest(total-paid_amount,0)) stored, financial_status public.financial_status not null default 'aguardando_pagamento', operational_status text not null default 'novo', production_status text not null default 'nao_aplicavel', installation_status text not null default 'nao_aplicavel', current_responsible_id uuid references public.profiles(id), next_action text, next_action_date date, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,sale_number));
create table public.sale_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), sale_id uuid not null references public.sales(id) on delete cascade, product text not null, description text, unit text not null default 'un', quantity numeric(14,3) not null check(quantity>0), unit_price numeric(14,2) not null check(unit_price>=0), total numeric(14,2) generated always as (quantity*unit_price) stored, requires_purchase boolean not null default false, requires_production boolean not null default false, notes text);

create table public.quotes (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), quote_number text not null, client_id uuid not null references public.clients(id), sale_type_id uuid not null references public.sale_types(id), seller_id uuid references public.profiles(id), subtotal numeric(14,2) not null default 0, discount numeric(14,2) not null default 0, freight numeric(14,2) not null default 0, total numeric(14,2) generated always as (greatest(subtotal-discount+freight,0)) stored, status text not null default 'rascunho', valid_until date, notes text, approved_at timestamptz, sale_id uuid references public.sales(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,quote_number));
create table public.quote_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), quote_id uuid not null references public.quotes(id) on delete cascade, product text not null, description text, unit text not null default 'un', quantity numeric(14,3) not null check(quantity>0), unit_price numeric(14,2) not null check(unit_price>=0), total numeric(14,2) generated always as (quantity*unit_price) stored, requires_purchase boolean not null default false, requires_production boolean not null default false);
create table public.gutter_quotes (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), quote_id uuid not null unique references public.quotes(id) on delete cascade, created_at timestamptz default now());
create table public.gutter_quote_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), gutter_quote_id uuid not null references public.gutter_quotes(id) on delete cascade, product text not null, thickness text not null, cut text not null, quantity numeric(14,3) not null, meters numeric(14,3) not null, unit_price numeric(14,2) not null, total numeric(14,2) generated always as (quantity*meters*unit_price) stored);

create table public.orders (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), order_number text not null, sale_id uuid not null unique references public.sales(id), client_id uuid not null references public.clients(id), sale_type_id uuid not null references public.sale_types(id), operational_status text not null default 'novo', purchase_status text not null default 'nao_solicitado', production_status text not null default 'nao_liberado', installation_status text not null default 'nao_agendada', current_responsible_id uuid references public.profiles(id), next_action text, next_action_date date, blocked_reason text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,order_number));
create table public.order_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), order_id uuid not null references public.orders(id) on delete cascade, sale_item_id uuid references public.sale_items(id), product text not null, description text, unit text not null default 'un', quantity numeric(14,3) not null, notes text);

create table public.checklist_templates (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), sale_type_id uuid references public.sale_types(id), name text not null, active boolean not null default true, is_default boolean not null default false, created_at timestamptz default now());
create table public.checklist_template_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), template_id uuid not null references public.checklist_templates(id) on delete cascade, title text not null, default_role public.app_role, required boolean not null default true, sort_order integer not null, due_days integer, unique(template_id,sort_order));
create table public.order_checklists (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), order_id uuid not null unique references public.orders(id) on delete cascade, template_id uuid references public.checklist_templates(id), status public.checklist_status not null default 'pendente', created_at timestamptz default now(), completed_at timestamptz);
create table public.order_checklist_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), checklist_id uuid not null references public.order_checklists(id) on delete cascade, order_id uuid not null references public.orders(id) on delete cascade, title text not null, status public.checklist_status not null default 'pendente', responsible_id uuid references public.profiles(id), due_date date, completed_at timestamptz, notes text, attachment_url text, required boolean not null default true, sort_order integer not null);

create table public.supplier_categories (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), name text not null, unique(company_id,name));
create table public.suppliers (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), category_id uuid references public.supplier_categories(id), name text not null, tax_id text, phone text, whatsapp text, email text, city text, state char(2), average_lead_days integer, payment_terms text, notes text, status public.record_status not null default 'ativo', created_at timestamptz default now(), updated_at timestamptz default now());
create table public.purchase_requests (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), request_number text not null, order_id uuid references public.orders(id), requested_by uuid references public.profiles(id), approved_by uuid references public.profiles(id), status text not null default 'solicitacao_criada', needed_by date, notes text, created_at timestamptz default now(), unique(company_id,request_number));
create table public.purchase_request_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), request_id uuid not null references public.purchase_requests(id) on delete cascade, material_id uuid, description text not null, unit text not null, requested_quantity numeric(14,3) not null, supplier_id uuid references public.suppliers(id), notes text);
create table public.purchase_orders (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), order_number text not null, request_id uuid references public.purchase_requests(id), order_id uuid references public.orders(id), supplier_id uuid not null references public.suppliers(id), buyer_id uuid references public.profiles(id), status text not null default 'solicitacao_criada', total numeric(14,2) not null default 0, paid_amount numeric(14,2) not null default 0, open_amount numeric(14,2) generated always as (greatest(total-paid_amount,0)) stored, ordered_at date, expected_at date, received_at date, notes text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(company_id,order_number));
create table public.purchase_order_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade, material_id uuid, category text, description text not null, unit text not null, requested_quantity numeric(14,3) not null default 0, purchased_quantity numeric(14,3) not null default 0, received_quantity numeric(14,3) not null default 0, pending_quantity numeric(14,3) generated always as (greatest(purchased_quantity-received_quantity,0)) stored, unit_price numeric(14,2) not null default 0, total numeric(14,2) generated always as (purchased_quantity*unit_price) stored, supplier_id uuid references public.suppliers(id), status text not null default 'pendente', client_id uuid references public.clients(id), sale_id uuid references public.sales(id), order_id uuid references public.orders(id), required_for_production boolean not null default true, notes text);

create table public.material_categories (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), name text not null, unique(company_id,name));
create table public.materials (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), category_id uuid references public.material_categories(id), sku text, name text not null, unit text not null, minimum_stock numeric(14,3) not null default 0, active boolean not null default true, unique(company_id,sku));
alter table public.purchase_request_items add constraint purchase_request_material_fk foreign key(material_id) references public.materials(id);
alter table public.purchase_order_items add constraint purchase_order_material_fk foreign key(material_id) references public.materials(id);
create table public.stock_locations (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), name text not null, active boolean not null default true, unique(company_id,name));
create table public.stock_movements (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), material_id uuid not null references public.materials(id), location_id uuid not null references public.stock_locations(id), movement_type text not null check(movement_type in ('entrada','saida','reserva','baixa_producao','baixa_venda_direta','ajuste','devolucao','perda')), quantity numeric(14,3) not null check(quantity<>0), unit_cost numeric(14,2), purchase_order_item_id uuid references public.purchase_order_items(id), order_id uuid references public.orders(id), notes text, created_by uuid references public.profiles(id), created_at timestamptz default now());

create table public.production_orders (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), production_number text not null, order_id uuid not null references public.orders(id), status text not null default 'aguardando_material', planned_start date, planned_end date, started_at timestamptz, finished_at timestamptz, responsible_id uuid references public.profiles(id), notes text, created_at timestamptz default now(), unique(company_id,production_number));
create table public.production_order_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), production_order_id uuid not null references public.production_orders(id) on delete cascade, order_item_id uuid references public.order_items(id), description text not null, quantity numeric(14,3) not null, status text not null default 'pendente', notes text);
create table public.production_materials (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), production_order_id uuid not null references public.production_orders(id) on delete cascade, material_id uuid not null references public.materials(id), required_quantity numeric(14,3) not null, received_quantity numeric(14,3) not null default 0, reserved_quantity numeric(14,3) not null default 0, required boolean not null default true, status text not null default 'nao_solicitado', notes text);

create table public.installations (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), order_id uuid not null references public.orders(id), responsible_id uuid references public.profiles(id), scheduled_at timestamptz, completed_at timestamptz, address text, status text not null default 'nao_agendada', notes text, created_at timestamptz default now());
create table public.installation_checklists (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), installation_id uuid not null references public.installations(id) on delete cascade, title text not null, completed boolean not null default false, completed_at timestamptz, notes text, sort_order integer not null);

create table public.financial_entries (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), entry_type public.financial_entry_type not null, origin text not null check(origin in ('venda','compra','manual','comissao','despesa','ajuste')), client_id uuid references public.clients(id), supplier_id uuid references public.suppliers(id), sale_id uuid references public.sales(id), purchase_order_id uuid references public.purchase_orders(id), description text not null, total_amount numeric(14,2) not null check(total_amount>=0), paid_amount numeric(14,2) not null default 0 check(paid_amount>=0), open_amount numeric(14,2) generated always as (greatest(total_amount-paid_amount,0)) stored, due_date date, paid_at date, payment_method text, status public.financial_status not null default 'aguardando_pagamento', notes text, created_at timestamptz default now(), updated_at timestamptz default now(), check((entry_type='receber' and supplier_id is null) or (entry_type='pagar' and client_id is null)));
create table public.payments (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), financial_entry_id uuid not null references public.financial_entries(id) on delete restrict, amount numeric(14,2) not null check(amount>0), paid_at date not null, payment_method text, receipt_url text, notes text, created_by uuid references public.profiles(id), created_at timestamptz default now());
create table public.commissions (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), sale_id uuid not null references public.sales(id), profile_id uuid not null references public.profiles(id), percentage numeric(6,3), amount numeric(14,2) not null, status text not null default 'pendente', due_date date, paid_at date);

create table public.pipeline_stages (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), name text not null, color text, sort_order integer not null, is_won boolean default false, is_lost boolean default false);
create table public.leads (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), client_id uuid references public.clients(id), name text not null, phone text, email text, source text, stage_id uuid references public.pipeline_stages(id), owner_id uuid references public.profiles(id), estimated_value numeric(14,2), next_action text, next_action_date date, status text not null default 'aberto', notes text, created_at timestamptz default now());
create table public.activities (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), client_id uuid references public.clients(id), lead_id uuid references public.leads(id), sale_id uuid references public.sales(id), activity_type text not null, subject text not null, description text, occurred_at timestamptz default now(), created_by uuid references public.profiles(id));
create table public.tasks (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), title text not null, description text, assigned_to uuid references public.profiles(id), due_at timestamptz, status text not null default 'pendente', priority text not null default 'normal', related_type text, related_id uuid, created_at timestamptz default now());
create table public.followups (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), client_id uuid references public.clients(id), lead_id uuid references public.leads(id), sale_id uuid references public.sales(id), responsible_id uuid references public.profiles(id), due_at timestamptz not null, action text not null, status text not null default 'pendente', completed_at timestamptz, notes text);

create table public.conversations (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), client_id uuid references public.clients(id), channel text not null, external_id text, status text not null default 'aberta', assigned_to uuid references public.profiles(id), created_at timestamptz default now());
create table public.messages (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), conversation_id uuid not null references public.conversations(id) on delete cascade, direction text not null, body text, media_url text, sent_at timestamptz default now(), sent_by uuid references public.profiles(id));
create table public.campaigns (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), name text not null, channel text not null, status text not null default 'rascunho', content text, scheduled_at timestamptz, created_by uuid references public.profiles(id), created_at timestamptz default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), profile_id uuid not null references public.profiles(id), title text not null, body text, link text, read_at timestamptz, created_at timestamptz default now());
create table public.files (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), bucket text not null, path text not null, file_name text not null, mime_type text, size_bytes bigint, related_type text, related_id uuid, uploaded_by uuid references public.profiles(id), created_at timestamptz default now());
create table public.audit_logs (id bigint generated always as identity primary key, company_id uuid not null references public.companies(id), profile_id uuid references public.profiles(id), table_name text not null, record_id uuid, action text not null, old_data jsonb, new_data jsonb, created_at timestamptz default now());

create index financial_due_idx on public.financial_entries(company_id,status,due_date);
create index purchase_order_status_idx on public.purchase_orders(company_id,status,expected_at);
create index checklist_order_idx on public.order_checklist_items(order_id,sort_order);
create index stock_material_idx on public.stock_movements(company_id,material_id,location_id);
